# Generated by Django 3.2.13 on 2022-06-06 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('information', models.TextField()),
                ('collection', models.CharField(blank=True, choices=[('base', 'base'), ('forms', 'forms'), ('lists', 'lists'), ('semantic', 'semantic'), ('tables', 'tables')], max_length=10, null=True)),
                ('experimental', models.BooleanField(default=False)),
                ('meta', models.BooleanField(default=False)),
                ('self_closing', models.BooleanField(default=False)),
                ('inline', models.BooleanField(default=False)),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElementExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_code', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_end_book.element')),
            ],
        ),
        migrations.CreateModel(
            name='ElementAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('information', models.TextField()),
                ('required', models.BooleanField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_end_book.element')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField()),
                ('information', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_end_book.elementattributes')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_end_book.element')),
            ],
        ),
    ]
